[package]
name = "cosmic-applet-notifications"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
icon-loader = { version = "0.3.6", features = ["gtk"] }
libcosmic = { git = "https://github.com/pop-os/libcosmic/", branch = "master", default-features = false, features = ["wayland", "applet"] }
nix = "0.24.1"
zbus = { version = "3", default-features = false, features = ["tokio"] }
