[package]
name = "cosmic-applet-minimize"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
image = "0.24"
libcosmic.workspace = true
memmap2 = "0.9.0"
rustix = { version = "0.38.0", features = ["fs"] }
png = "0.17.5"
tokio = { version = "1.17.0", features = ["sync", "macros"] }
tracing = "0.1.40"
tracing-subscriber.workspace = true
tracing-log.workspace = true
tempfile = "3.5.0"
# Application i18n
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6"
rust-embed = "6.6"
rust-embed-utils = "7.5.0"
once_cell = "1"
