[package]
name = "cosmic-panel-button"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
freedesktop-desktop-entry = "0.6.2"
libcosmic.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
cosmic-config.workspace = true
serde.workspace = true
