[package]
name = "cosmic-applet-power"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
icon-loader = { version = "0.3.6", features = ["gtk"] }
libpulse-binding = "2.26.0"
libpulse-glib-binding = "2.25.0"
tokio = { version = "1.20.1", features=["full"] }
libcosmic = { git = "https://github.com/pop-os/libcosmic/", branch = "master", default-features = false, features = ["wayland", "applet"] }
sctk = { package = "smithay-client-toolkit", git = "https://github.com/Smithay/client-toolkit", rev = "3776d4a" }
nix = "0.26.1"

# Until the 3.6.3 release, need the implementation of clone on zbus::Error
[dependencies.zbus]
git = "https://gitlab.freedesktop.org/dbus/zbus"
branch = "main"

# Until zbus 3.6.3 is released
[dependencies.logind-zbus]
git = "https://github.com/pop-os/logind-zbus"
branch = "main"
