[package]
name = "cosmic-applet-battery"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
cosmic-settings-subscriptions.workspace = true
cosmic-time.workspace = true
drm = "0.11.1"
futures.workspace = true
i18n-embed-fl.workspace = true
i18n-embed.workspace = true
libcosmic.workspace = true
once_cell = "1.19.0"
rust-embed.workspace = true
tokio = { version = "1.36.0", features = ["sync", "rt", "rt-multi-thread", "fs", "macros"] }
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
udev = "0.8"
zbus.workspace = true
