[package]
name = "cosmic-app-list-config"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcosmic.workspace = true
serde = { workspace = true, features = ["derive"] }
