[package]
name = "cosmic-applet-time"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
chrono = { version = "0.4.35", features = ["clock"] }
chrono-tz = "0.9"
i18n-embed-fl.workspace = true
i18n-embed.workspace = true
libcosmic.workspace = true
once_cell = "1"
rust-embed.workspace = true
tokio = { version = "1.36.0", features = ["time"] }
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
icu = { version = "1.4.0", features = ["experimental", "compiled_data", "icu_datetime_experimental"]}
zbus.workspace = true
timedate-zbus = { git = "https://github.com/pop-os/dbus-settings-bindings" }
