[package]
name = "cosmic-applet-network"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow.workspace = true
cosmic-dbus-networkmanager = { git = "https://github.com/pop-os/dbus-settings-bindings" }
cosmic-time.workspace = true
futures.workspace = true
futures-util.workspace = true
i18n-embed-fl.workspace = true
i18n-embed.workspace = true
itertools = "0.14.0"
libcosmic = { workspace = true, features = [
    "applet",
    "applet-token",
    "tokio",
    "wayland",
    "desktop",
] }
rust-embed.workspace = true
rustc-hash.workspace = true
tokio.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
zbus.workspace = true
